import '../models/game_model.dart';

/// Source of truth for the game catalog.
///
/// For this stage this returns a hand-written list of built-in games.
/// The shape is intentionally identical to what a remote/downloaded
/// catalog will look like later (Download Manager stage), so
/// switching to a mixed local+remote catalog later won't require
/// touching any screen — only this class grows a merge step.
class GameRepository {
  static final List<GameModel> _builtInGames = [
    const GameModel(
      id: 'snake',
      name: 'Snake',
      category: 'Arcade',
      description: 'Classic grid snake. Eat, grow, don\'t hit yourself or the walls.',
      rating: 4.6,
      sizeLabel: '1.2 MB',
      engineKey: 'snake',
      isPopular: true,
    ),
    const GameModel(
      id: 'tic_tac_toe',
      name: 'Tic-Tac-Toe',
      category: 'Puzzle',
      description: 'Local 2-player X/O on a 3x3 board.',
      rating: 4.3,
      sizeLabel: '0.6 MB',
      engineKey: 'tic_tac_toe',
    ),
    const GameModel(
      id: 'runner',
      name: 'Endless Runner',
      category: 'Arcade',
      description: 'Tap to jump over obstacles. Score increases with distance.',
      rating: 4.1,
      sizeLabel: '2.0 MB',
      engineKey: 'runner',
      isPopular: true,
    ),
    const GameModel(
      id: 'memory',
      name: 'Memory Puzzle',
      category: 'Brain',
      description: 'Flip cards and match all pairs in as few tries as possible.',
      rating: 4.4,
      sizeLabel: '0.9 MB',
      engineKey: 'memory',
    ),
    const GameModel(
      id: 'puzzle_2048',
      name: '2048',
      category: 'Puzzle',
      description: 'Swipe to merge matching tiles and reach 2048.',
      rating: 4.7,
      sizeLabel: '1.0 MB',
      engineKey: 'puzzle_2048',
      isPopular: true,
    ),
    const GameModel(
      id: 'whack_a_mole',
      name: 'Whack-a-Mole',
      category: 'Arcade',
      description: 'Tap the mole before it disappears. 30-second rounds.',
      rating: 4.2,
      sizeLabel: '1.1 MB',
      engineKey: 'whack_a_mole',
      isNew: true,
    ),
    const GameModel(
      id: 'reaction_time',
      name: 'Reaction Time',
      category: 'Brain',
      description: 'Tap the instant the screen turns green. Test your reflexes.',
      rating: 4.3,
      sizeLabel: '0.5 MB',
      engineKey: 'reaction_time',
      isNew: true,
    ),
    const GameModel(
      id: 'simon_says',
      name: 'Simon Says',
      category: 'Brain',
      description: 'Watch the color sequence, then repeat it. How far can you go?',
      rating: 4.5,
      sizeLabel: '0.7 MB',
      engineKey: 'simon_says',
      isNew: true,
    ),
    const GameModel(
      id: 'rock_paper_scissors',
      name: 'Rock Paper Scissors',
      category: 'Casual',
      description: 'Best of session against the computer.',
      rating: 4.0,
      sizeLabel: '0.5 MB',
      engineKey: 'rock_paper_scissors',
    ),
    const GameModel(
      id: 'number_guess',
      name: 'Number Guess',
      category: 'Brain',
      description: 'Guess the secret number between 1 and 100 in as few tries as possible.',
      rating: 4.1,
      sizeLabel: '0.4 MB',
      engineKey: 'number_guess',
    ),
    const GameModel(
      id: 'minesweeper',
      name: 'Minesweeper',
      category: 'Puzzle',
      description: 'Classic 8x8 minefield. Flag the mines, clear the rest.',
      rating: 4.6,
      sizeLabel: '1.3 MB',
      engineKey: 'minesweeper',
      isPopular: true,
    ),
    const GameModel(
      id: 'connect_four',
      name: 'Connect Four',
      category: 'Puzzle',
      description: 'Local 2-player. Get four discs in a row to win.',
      rating: 4.4,
      sizeLabel: '1.0 MB',
      engineKey: 'connect_four',
    ),
    const GameModel(
      id: 'sliding_puzzle',
      name: '15 Puzzle',
      category: 'Puzzle',
      description: 'Slide the tiles back into numerical order.',
      rating: 4.2,
      sizeLabel: '0.8 MB',
      engineKey: 'sliding_puzzle',
    ),
    const GameModel(
      id: 'word_scramble',
      name: 'Word Scramble',
      category: 'Brain',
      description: 'Unscramble the letters to find the word.',
      rating: 4.3,
      sizeLabel: '0.6 MB',
      engineKey: 'word_scramble',
      isNew: true,
    ),
    const GameModel(
      id: 'higher_lower',
      name: 'Higher or Lower',
      category: 'Casual',
      description: 'Guess if the next card is higher or lower. Build your streak.',
      rating: 4.0,
      sizeLabel: '0.4 MB',
      engineKey: 'higher_lower',
    ),
    const GameModel(
      id: 'brick_breaker',
      name: 'Brick Breaker',
      category: 'Arcade',
      description: 'Drag to move the paddle and clear every brick.',
      rating: 4.5,
      sizeLabel: '1.4 MB',
      engineKey: 'brick_breaker',
      isPopular: true,
    ),
    const GameModel(
      id: 'dice_duel',
      name: 'Dice Duel',
      category: 'Casual',
      description: 'Best of 5 rounds against the CPU. Highest roll wins the round.',
      rating: 4.0,
      sizeLabel: '0.5 MB',
      engineKey: 'dice_duel',
    ),
    const GameModel(
      id: 'fruit_slice',
      name: 'Fruit Slice',
      category: 'Arcade',
      description: 'Tap falling fruits for points — avoid the bombs!',
      rating: 4.4,
      sizeLabel: '1.2 MB',
      engineKey: 'fruit_slice',
      isNew: true,
    ),
    const GameModel(
      id: 'flappy_block',
      name: 'Flappy Block',
      category: 'Arcade',
      description: 'Tap to fly through the gaps. One touch, one life.',
      rating: 4.3,
      sizeLabel: '1.0 MB',
      engineKey: 'flappy_block',
      isNew: true,
      isPopular: true,
    ),
    const GameModel(
      id: 'pong',
      name: 'Pong',
      category: 'Arcade',
      description: 'Classic paddle vs paddle. First to 5 points wins.',
      rating: 4.2,
      sizeLabel: '0.9 MB',
      engineKey: 'pong',
    ),
    const GameModel(
      id: 'hangman',
      name: 'Hangman',
      category: 'Brain',
      description: 'Guess the word one letter at a time before you run out of tries.',
      rating: 4.3,
      sizeLabel: '0.6 MB',
      engineKey: 'hangman',
    ),
    const GameModel(
      id: 'speed_math',
      name: 'Speed Math',
      category: 'Brain',
      description: 'Solve as many arithmetic problems as you can in 60 seconds.',
      rating: 4.4,
      sizeLabel: '0.5 MB',
      engineKey: 'speed_math',
      isNew: true,
    ),
    const GameModel(
      id: 'quiz_trivia',
      name: 'Quiz Trivia',
      category: 'Brain',
      description: 'General-knowledge multiple-choice quiz.',
      rating: 4.2,
      sizeLabel: '0.8 MB',
      engineKey: 'quiz_trivia',
    ),
    const GameModel(
      id: 'battleship',
      name: 'Battleship',
      category: 'Puzzle',
      description: 'Find all the hidden ships in as few shots as possible.',
      rating: 4.3,
      sizeLabel: '1.1 MB',
      engineKey: 'battleship',
    ),
    const GameModel(
      id: 'maze_escape',
      name: 'Maze Escape',
      category: 'Puzzle',
      description: 'Navigate a randomly generated maze to the exit.',
      rating: 4.1,
      sizeLabel: '0.9 MB',
      engineKey: 'maze_escape',
      isNew: true,
    ),
    const GameModel(
      id: 'color_match',
      name: 'Color Match',
      category: 'Casual',
      description: 'Does the word match its ink color? Test your focus under pressure.',
      rating: 4.0,
      sizeLabel: '0.5 MB',
      engineKey: 'color_match',
    ),
    const GameModel(
      id: 'tetris_lite',
      name: 'Tetris Lite',
      category: 'Arcade',
      description: 'Classic falling-block stacking. Clear full lines for points.',
      rating: 4.6,
      sizeLabel: '1.3 MB',
      engineKey: 'tetris_lite',
      isPopular: true,
    ),
    const GameModel(
      id: 'sokoban_mini',
      name: 'Sokoban Mini',
      category: 'Puzzle',
      description: 'Push every box onto its target across 3 compact levels.',
      rating: 4.3,
      sizeLabel: '0.9 MB',
      engineKey: 'sokoban_mini',
    ),
    const GameModel(
      id: 'sudoku_classic',
      name: 'Sudoku',
      category: 'Puzzle',
      description: 'Classic 9x9 Sudoku. Fill every row, column and box with 1-9.',
      rating: 4.5,
      sizeLabel: '1.0 MB',
      engineKey: 'sudoku_classic',
      isPopular: true,
    ),
    const GameModel(
      id: 'target_shooter',
      name: 'Target Shooter',
      category: 'Arcade',
      description: 'Tap moving targets before they escape. Gold targets score more.',
      rating: 4.2,
      sizeLabel: '1.1 MB',
      engineKey: 'target_shooter',
      isNew: true,
    ),
    const GameModel(
      id: 'tug_of_war',
      name: 'Tug of War',
      category: 'Casual',
      description: 'Tap as fast as you can to pull the rope past the CPU.',
      rating: 4.0,
      sizeLabel: '0.4 MB',
      engineKey: 'tug_of_war',
    ),
    const GameModel(
      id: 'coin_flip_streak',
      name: 'Coin Flip Streak',
      category: 'Casual',
      description: 'Predict heads or tails and build the longest streak.',
      rating: 3.9,
      sizeLabel: '0.3 MB',
      engineKey: 'coin_flip_streak',
    ),
    const GameModel(
      id: 'anagram_hunter',
      name: 'Anagram Hunter',
      category: 'Brain',
      description: 'Find as many hidden words as you can in the given letters.',
      rating: 4.2,
      sizeLabel: '0.7 MB',
      engineKey: 'anagram_hunter',
      isNew: true,
    ),
    const GameModel(
      id: 'odd_one_out',
      name: 'Odd One Out',
      category: 'Brain',
      description: 'Spot the subtly different tile before time runs out.',
      rating: 4.1,
      sizeLabel: '0.5 MB',
      engineKey: 'odd_one_out',
    ),
    const GameModel(
      id: 'bubble_pop_match',
      name: 'Bubble Pop',
      category: 'Puzzle',
      description: 'Pop connected groups of same-colored bubbles for points.',
      rating: 4.4,
      sizeLabel: '1.0 MB',
      engineKey: 'bubble_pop_match',
      isPopular: true,
    ),
    const GameModel(
      id: 'balloon_inflate',
      name: 'Balloon Inflate',
      category: 'Casual',
      description: 'Hold to inflate and release right at the hidden target size.',
      rating: 3.9,
      sizeLabel: '0.5 MB',
      engineKey: 'balloon_inflate',
    ),
    const GameModel(
      id: 'air_hockey',
      name: 'Air Hockey',
      category: 'Arcade',
      description: 'Drag your mallet to defend and score against the CPU.',
      rating: 4.3,
      sizeLabel: '1.2 MB',
      engineKey: 'air_hockey',
      isNew: true,
    ),
    const GameModel(
      id: 'reflex_sequence',
      name: 'Reflex Sequence',
      category: 'Brain',
      description: 'Tap the scattered numbers 1 through 15 in order, as fast as possible.',
      rating: 4.0,
      sizeLabel: '0.5 MB',
      engineKey: 'reflex_sequence',
    ),
    const GameModel(
      id: 'wordle',
      name: 'Wordle',
      category: 'Brain',
      description: 'Guess the hidden 5-letter word in 6 tries with color feedback.',
      rating: 4.7,
      sizeLabel: '0.8 MB',
      engineKey: 'wordle',
      isPopular: true,
    ),
    const GameModel(
      id: 'alien_shooter',
      name: 'Alien Shooter',
      category: 'Arcade',
      description: 'Classic descending-alien shooter. Drag to move, tap to fire.',
      rating: 4.5,
      sizeLabel: '1.5 MB',
      engineKey: 'alien_shooter',
      isPopular: true,
    ),
    const GameModel(
      id: 'checkers',
      name: 'Checkers',
      category: 'Puzzle',
      description: 'Local 2-player draughts on an 8x8 board.',
      rating: 4.3,
      sizeLabel: '1.1 MB',
      engineKey: 'checkers',
    ),
    const GameModel(
      id: 'tower_of_hanoi',
      name: 'Tower of Hanoi',
      category: 'Brain',
      description: 'Move the whole stack of disks to the last peg in as few moves as possible.',
      rating: 4.2,
      sizeLabel: '0.6 MB',
      engineKey: 'tower_of_hanoi',
    ),
    const GameModel(
      id: 'peg_solitaire',
      name: 'Peg Solitaire',
      category: 'Puzzle',
      description: 'Jump pegs over each other to clear the board down to one.',
      rating: 4.1,
      sizeLabel: '0.7 MB',
      engineKey: 'peg_solitaire',
    ),
    const GameModel(
      id: 'blackjack',
      name: 'Blackjack',
      category: 'Casual',
      description: 'Simplified 21 against a dealer that hits to 17.',
      rating: 4.3,
      sizeLabel: '0.7 MB',
      engineKey: 'blackjack',
      isNew: true,
    ),
    const GameModel(
      id: 'basketball_shootout',
      name: 'Basketball Shootout',
      category: 'Arcade',
      description: 'Drag back and release to arc the ball into the hoop. 30-second rounds.',
      rating: 4.2,
      sizeLabel: '1.2 MB',
      engineKey: 'basketball_shootout',
      isNew: true,
    ),
    const GameModel(
      id: 'rhythm_tap',
      name: 'Rhythm Tap',
      category: 'Arcade',
      description: 'Tap the lane as each note crosses the line. Build your combo.',
      rating: 4.4,
      sizeLabel: '1.0 MB',
      engineKey: 'rhythm_tap',
      isNew: true,
    ),
    const GameModel(
      id: 'darts',
      name: 'Darts',
      category: 'Casual',
      description: 'Time your throw as the crosshair sweeps the board. 5 darts per game.',
      rating: 4.1,
      sizeLabel: '0.8 MB',
      engineKey: 'darts',
    ),
  ];

  List<GameModel> getAll() => List.unmodifiable(_builtInGames);

  List<GameModel> getPopular() => _builtInGames.where((g) => g.isPopular).toList();

  List<GameModel> getNew() => _builtInGames.where((g) => g.isNew).toList();

  List<GameModel> getByCategory(String category) =>
      _builtInGames.where((g) => g.category == category).toList();

  List<String> getCategories() =>
      _builtInGames.map((g) => g.category).toSet().toList()..sort();

  List<GameModel> search(String query) {
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return getAll();
    return _builtInGames
        .where((g) =>
            g.name.toLowerCase().contains(q) ||
            g.category.toLowerCase().contains(q))
        .toList();
  }

  GameModel? byId(String id) {
    for (final g in _builtInGames) {
      if (g.id == id) return g;
    }
    return null;
  }
}
