Run PUBSPEC_PATH=$(find . -name "pubspec.yaml" -not -path "*/.*" | head -n 1)
Recreating project ....
  gamebox.iml (created)
  android/gradle/wrapper/gradle-wrapper.properties (created)
  android/app/src/debug/AndroidManifest.xml (created)
  android/app/src/profile/AndroidManifest.xml (created)
  android/app/src/main/AndroidManifest.xml (created)
  android/app/src/main/res/values/styles.xml (created)
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  android/app/src/main/res/drawable/launch_background.xml (created)
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  android/app/src/main/res/drawable-v21/launch_background.xml (created)
  android/app/src/main/res/values-night/styles.xml (created)
  android/settings.gradle.kts (created)
  android/.gitignore (created)
  android/gradle.properties (created)
  android/app/build.gradle.kts (created)
  android/app/src/main/kotlin/com/example/gamebox/MainActivity.kt (created)
  android/gamebox_android.iml (created)
  android/build.gradle.kts (created)
  .idea/libraries/KotlinJavaRuntime.xml (created)
  .idea/libraries/Dart_SDK.xml (created)
  .idea/runConfigurations/main_dart.xml (created)
  .idea/modules.xml (created)
  .idea/workspace.xml (created)
  .gitignore (created)
Resolving dependencies...
Downloading packages...
Got dependencies.
Upgrading analysis_options.yaml to exclude build and platform directories.
Wrote 30 files.

All done!
You can find general documentation for Flutter at: https://docs.flutter.dev/
Detailed API documentation is available at: https://api.flutter.dev/
If you prefer video documentation, consider: https://www.youtube.com/c/flutterdev

In order to run your application, type:

  $ flutter run

Your application code is in ./lib/main.dart.

Resolving dependencies...
Downloading packages...
  archive 3.6.1 (4.3.0 available)
  cli_util 0.4.2 (0.6.0 available)
  file_picker 8.3.7 (13.1.0 available)
  flutter_lints 4.0.0 (6.0.0 available)
  flutter_native_splash 2.4.4 (2.4.8 available)
  google_sign_in 6.3.0 (7.2.0 available)
  google_sign_in_android 6.2.1 (7.2.17 available)
  google_sign_in_ios 5.9.0 (6.3.3 available)
  google_sign_in_platform_interface 2.5.0 (3.1.0 available)
  google_sign_in_web 0.12.4+4 (1.1.3 available)
  image 4.3.0 (4.10.1 available)
  lints 4.0.0 (6.1.0 available)
  material_color_utilities 0.13.0 (0.13.1 available)
  meta 1.18.3 (1.19.0 available)
  test_api 0.7.12 (0.7.14 available)
  vector_math 2.4.0 (2.4.2 available)
  win32 5.15.0 (6.4.0 available)
  xml 6.6.1 (7.0.1 available)
Got dependencies!
18 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Running Gradle task 'assembleDebug'...                          
Checking the license for package Android SDK Platform 31 in /usr/local/lib/android/sdk/licenses
License for package Android SDK Platform 31 accepted.
Preparing "Install Android SDK Platform 31 (revision 1)".
"Install Android SDK Platform 31 (revision 1)" ready.
Installing Android SDK Platform 31 in /usr/local/lib/android/sdk/platforms/android-31
"Install Android SDK Platform 31 (revision 1)" complete.
"Install Android SDK Platform 31 (revision 1)" finished.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':file_picker:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > An issue was found when checking AAR metadata:

       1.  Dependency ':flutter_plugin_android_lifecycle' requires libraries and applications that
           depend on it to compile against version 36 or later of the
           Android APIs.

           :file_picker is currently compiled against android-34.

           Recommended action: Update this project to use a newer compileSdk
           of at least 36, for example 36.

           Note that updating a library or application's compileSdk (which
           allows newer APIs to be used) can be done separately from updating
           targetSdk (which opts the app in to new runtime behavior) and
           minSdk (which determines which devices the app can be installed
           on).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights from a Build Scan (powered by Develocity).
> Get more help at https://help.gradle.org.

BUILD FAILED in 4m 11s
[=========                              ] 25%                                   
Running Gradle task 'assembleDebug'...                            252.0s
Gradle task assembleDebug failed with exit code 1
Error: Process completed with exit code 1.
